export const NO_VOLUME_DISCOUNT = 0.3;
export const LARGE_VOLUME_DISCOUNT = 0.45;

export const ACTIVE_DISCOUNT_REDUCTION = (1 - NO_VOLUME_DISCOUNT);
export const INACTIVE_DISCOUNT_REDUCTION = (1 - LARGE_VOLUME_DISCOUNT);
