// tslint:disable: object-literal-key-quotes
import { FlavourMap } from "@shared/models/types/flavour.type";

const FLAVOUR_FOLDER_PATH = "/assets/icons/flavours/";

export const FLAVOUR_MAP: FlavourMap = {
    "almond": `${FLAVOUR_FOLDER_PATH}almond.svg`,
    "apple": `${FLAVOUR_FOLDER_PATH}apple.svg`,
    "apricot": `${FLAVOUR_FOLDER_PATH}peach.svg`,
    "bergamot": `${FLAVOUR_FOLDER_PATH}bergamot.svg`,
    "black-tea": `${FLAVOUR_FOLDER_PATH}black-tea.svg`,
    "blackberry": `${FLAVOUR_FOLDER_PATH}blackberry.svg`,
    "cacao": `${FLAVOUR_FOLDER_PATH}cacao.svg`,
    "cacao-nibs": `${FLAVOUR_FOLDER_PATH}cacao.svg`,
    "candy": `${FLAVOUR_FOLDER_PATH}candy.svg`,
    "cane-sugar": `${FLAVOUR_FOLDER_PATH}cane-sugar.svg`,
    "caramel": `${FLAVOUR_FOLDER_PATH}caramel.svg`,
    "cardamom": `${FLAVOUR_FOLDER_PATH}cardamom.svg`,
    "cherry": `${FLAVOUR_FOLDER_PATH}cherry.svg`,
    "cherry-blossom": `${FLAVOUR_FOLDER_PATH}cherry.svg`,
    "chocolate": `${FLAVOUR_FOLDER_PATH}chocolate.svg`,
    "cinnamon": `${FLAVOUR_FOLDER_PATH}cinnamon.svg`,
    "cocoa": `${FLAVOUR_FOLDER_PATH}chocolate.svg`,
    "coconut": `${FLAVOUR_FOLDER_PATH}coconut.svg`,
    "dark-chocolate": `${FLAVOUR_FOLDER_PATH}chocolate.svg`,
    "figs": `${FLAVOUR_FOLDER_PATH}figs.svg`,
    "floral": `${FLAVOUR_FOLDER_PATH}rose.svg`,
    "grapefruit": `${FLAVOUR_FOLDER_PATH}grapefruit.svg`,
    "grapes": `${FLAVOUR_FOLDER_PATH}grapes.svg`,
    "green-apple": `${FLAVOUR_FOLDER_PATH}green-apple.svg`,
    "guava": `${FLAVOUR_FOLDER_PATH}guava.svg`,
    "hibiscus": `${FLAVOUR_FOLDER_PATH}hibiscus.svg`,
    "honey": `${FLAVOUR_FOLDER_PATH}honey.svg`,
    "honeycomb": `${FLAVOUR_FOLDER_PATH}honeycomb.svg`,
    "kiwi": `${FLAVOUR_FOLDER_PATH}kiwi.svg}`,
    "lemon": `${FLAVOUR_FOLDER_PATH}lemon.svg`,
    "lemon-peel": `${FLAVOUR_FOLDER_PATH}lemon.svg`,
    "lychee": `${FLAVOUR_FOLDER_PATH}lychee.svg`,
    "mango": `${FLAVOUR_FOLDER_PATH}mango.svg`,
    "marshmallow": `${FLAVOUR_FOLDER_PATH}marshmallow.svg`,
    "molasses": `${FLAVOUR_FOLDER_PATH}molasses.svg`,
    "nutella": `${FLAVOUR_FOLDER_PATH}nutella.svg`,
    "orange-blossom": `${FLAVOUR_FOLDER_PATH}orange-blossom.svg`,
    "orange": `${FLAVOUR_FOLDER_PATH}orange.svg`,
    "papaya": `${FLAVOUR_FOLDER_PATH}guava.svg`,
    "peach": `${FLAVOUR_FOLDER_PATH}peach.svg`,
    "pecan": `${FLAVOUR_FOLDER_PATH}pecan.svg`,
    "pear": `${FLAVOUR_FOLDER_PATH}pear.svg`,
    "pineapple": `${FLAVOUR_FOLDER_PATH}pineapple.svg}`,
    "pistachio": `${FLAVOUR_FOLDER_PATH}pistachio.svg}`,
    "plum": `${FLAVOUR_FOLDER_PATH}plum.svg`,
    "pomegranate": `${FLAVOUR_FOLDER_PATH}pomegranate.svg`,
    "pomelo": `${FLAVOUR_FOLDER_PATH}pomelo.svg`,
    "raspberry": `${FLAVOUR_FOLDER_PATH}raspberry.svg`,
    "red-berries": `${FLAVOUR_FOLDER_PATH}red-berries.svg`,
    "red-fruits": `${FLAVOUR_FOLDER_PATH}red-berries.svg`,
    "red-ripe-fruits": `${FLAVOUR_FOLDER_PATH}red-berries.svg`,
    "ripe-fruits": `${FLAVOUR_FOLDER_PATH}red-berries.svg`,
    "red-currant": `${FLAVOUR_FOLDER_PATH}red-currant.svg`,
    "rhubarb": `${FLAVOUR_FOLDER_PATH}rhubarb.svg`,
    "rooibos": `${FLAVOUR_FOLDER_PATH}rooibos.svg`,
    "rose": `${FLAVOUR_FOLDER_PATH}rose.svg`,
    "rose-hips": `${FLAVOUR_FOLDER_PATH}rose.svg`,
    "sparkling": `${FLAVOUR_FOLDER_PATH}bubble.svg`,
    "strawberry": `${FLAVOUR_FOLDER_PATH}strawberry.svg`,
    "sugar": `${FLAVOUR_FOLDER_PATH}cane-sugar.svg`,
    "tangerine": `${FLAVOUR_FOLDER_PATH}tangerine.svg`,
    "toffee": `${FLAVOUR_FOLDER_PATH}toffee.svg`,
    "vanilla": `${FLAVOUR_FOLDER_PATH}vanilla.svg`,
    "vanilla-cake": `${FLAVOUR_FOLDER_PATH}vanilla-cake.svg`,
    "watermelon": `${FLAVOUR_FOLDER_PATH}watermelon.svg`,
    "white-flower": `${FLAVOUR_FOLDER_PATH}white-flower.svg`,
};
