// tslint:disable: object-literal-key-quotes
import { FlavourMap } from "@shared/models/types/flavour.type";

const FLAVOUR_FOLDER_PATH = "/assets/icons/flavours/";

export const FLAVOUR_MAP: FlavourMap = {
    "apple": `${FLAVOUR_FOLDER_PATH}apple.svg`,
    "bergamot": `${FLAVOUR_FOLDER_PATH}bergamot.svg`,
    "black-tea": `${FLAVOUR_FOLDER_PATH}black-tea.svg`,
    "cacao-nibs": `${FLAVOUR_FOLDER_PATH}cacao-nibs.svg`,
    "cane-sugar": `${FLAVOUR_FOLDER_PATH}cane-sugar.svg`,
    "caramel": `${FLAVOUR_FOLDER_PATH}caramel.svg`,
    "cherry": `${FLAVOUR_FOLDER_PATH}cherry.svg`,
    "chocolate": `${FLAVOUR_FOLDER_PATH}chocolate.svg`,
    "cinnamon": `${FLAVOUR_FOLDER_PATH}cinnamon.svg`,
    "coconut": `${FLAVOUR_FOLDER_PATH}coconut.svg`,
    "grapefruit": `${FLAVOUR_FOLDER_PATH}grapefruit.svg`,
    "grapes": `${FLAVOUR_FOLDER_PATH}grapes.svg`,
    "green-apple": `${FLAVOUR_FOLDER_PATH}green-apple.svg`,
    "hibiscus": `${FLAVOUR_FOLDER_PATH}hibiscus.svg`,
    "honey": `${FLAVOUR_FOLDER_PATH}honey.svg`,
    "honeycomb": `${FLAVOUR_FOLDER_PATH}honeycomb.svg`,
    "lemon": `${FLAVOUR_FOLDER_PATH}lemon.svg`,
    "marshmallow": `${FLAVOUR_FOLDER_PATH}marshmallow.svg`,
    "nutella": `${FLAVOUR_FOLDER_PATH}nutella.svg`,
    "orange-blossom": `${FLAVOUR_FOLDER_PATH}orange-blossom.svg`,
    "orange": `${FLAVOUR_FOLDER_PATH}orange.svg`,
    "peach": `${FLAVOUR_FOLDER_PATH}peach.svg`,
    "pear": `${FLAVOUR_FOLDER_PATH}pear.svg`,
    "pomegranate": `${FLAVOUR_FOLDER_PATH}pomegranate.svg`,
    "pomelo": `${FLAVOUR_FOLDER_PATH}pomelo.svg`,
    "raspberry": `${FLAVOUR_FOLDER_PATH}raspberry.svg`,
    "red-berries": `${FLAVOUR_FOLDER_PATH}red-berries.svg`,
    "red-currant": `${FLAVOUR_FOLDER_PATH}red-currant.svg`,
    "rhubarb": `${FLAVOUR_FOLDER_PATH}rhubarb.svg`,
    "rose": `${FLAVOUR_FOLDER_PATH}rose.svg`,
    "strawberry": `${FLAVOUR_FOLDER_PATH}strawberry.svg`,
    "tangerine": `${FLAVOUR_FOLDER_PATH}tangerine.svg`,
    "toffee": `${FLAVOUR_FOLDER_PATH}toffee.svg`,
    "vanilla": `${FLAVOUR_FOLDER_PATH}vanilla.svg`,
    "white-flower": `${FLAVOUR_FOLDER_PATH}white-flower.svg`,
};
