export const flavourIconMap = {
    "rhubarb":        "assets/svgs/flavour-icons/rhubarb.svg",
    "red berries":    "assets/svgs/flavour-icons/red-berries.svg",
    "pomelo":         "assets/svgs/flavour-icons/pomelo.svg",
    "cherry":         "assets/svgs/flavour-icons/cherry.svg",
    "white flower":   "assets/svgs/flavour-icons/white-flower.svg",
    "pomegranate":    "assets/svgs/flavour-icons/pomegranate.svg",
    "honeycomb":      "assets/svgs/flavour-icons/honeycomb.svg",
    "raspberry":      "assets/svgs/flavour-icons/raspberry.svg",
    "cinnamon":       "assets/svgs/flavour-icons/cinnamon.svg",
    "vanilla":        "assets/svgs/flavour-icons/vanilla.svg",
    "caramel":        "assets/svgs/flavour-icons/caramel.svg",
    "green apple":    "assets/svgs/flavour-icons/green-apple.svg",
    "red currant":    "assets/svgs/flavour-icons/red-currant.svg",
    "strawberry":     "assets/svgs/flavour-icons/strawberry.svg",
    "lemon":          "assets/svgs/flavour-icons/lemon.svg",
    "grapefruit":     "assets/svgs/flavour-icons/grapefruit.svg",
    "orange blossom": "assets/svgs/flavour-icons/orange-blossom.svg",
    "bergamot":       "assets/svgs/flavour-icons/bergamot.svg",
    "coconut":        "assets/svgs/flavour-icons/coconut.svg",
    "toffee":         "assets/svgs/flavour-icons/toffee.svg",
    "black tea":      "assets/svgs/flavour-icons/black-tea.svg",
    "grapes":         "assets/svgs/flavour-icons/grapes.svg",
    "hibiscus":       "assets/svgs/flavour-icons/hibiscus.svg",
    "pear":           "assets/svgs/flavour-icons/pear.svg",
    "peach":          "assets/svgs/flavour-icons/peach.svg",
    "orange":         "assets/svgs/flavour-icons/orange.svg",
    "marshmallow":    "assets/svgs/flavour-icons/marshmallow.svg",
    "cane sugar":     "assets/svgs/flavour-icons/cane-sugar.svg",
    "rose":           "assets/svgs/flavour-icons/rose.svg",
    "nutella":        "assets/svgs/flavour-icons/nutella.svg",
    "tangerine":      "assets/svgs/flavour-icons/tangerine.svg",
    "cacao nibs":     "assets/svgs/flavour-icons/cacao-nibs.svg",
};
